[package]
name = "glap-rs-server"
version = "0.1.0"
authors = ["Christian7573 <cag4561@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.async-std]
version = "1.6.2"
features = ["attributes", "unstable"]

[dependencies.async-tungstenite]
version = "0.8.0"
features = ["async-std-runtime"]

[dependencies]
nphysics2d = "0.16.1"
nalgebra = "0.21.1"
futures = "0.3.5"
rmp-serde = "0.14.4"
num-traits = "0.2.12"
ncollide2d = "0.23.2"

[dependencies.serde]
version = "1.0.114"
features = ["derive"]